name: JsDocs

on:
  push:
    branches:
      - master
      - test
  pull_request:
    branches: 
      - main 
      - test  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Search Page Docs
        run: npm run searchpageDocs



